### ISSUE TITLE
value error coming when the command model.learn executed

### ISSUE THREAD

**Issue by ghost** [sryu1/jsbgym#1]
model.learn(total_timesteps=10000000)
by this command , I am getting the error given below
ValueError: setting an array element with a sequ
<img width="779" alt="1" src="https://user-images.githubusercontent.com/125783843/219929900-a78d9e53-223b-4fa4-bda5-3b083a753b23.png">
<img width="832" alt="2" src="https://user-images.githubusercontent.com/125783843/219929907-b68ba01f-154d-483e-acd9-94681d674bb5.png">
ence. The requested array would exceed the maximum number of dimension of 1.

**Comment by sryu1** [comment]
I replied [here](https://github.com/sryu1/jsbgym-examples/issues/1), if what you did there doesn't work, I'll take a look at it from here.

**Comment by ghost** [comment]
The error is solved. The Training started.. Thank you so much. You are excellent programmer

**Comment by sryu1** [comment]
Nice, thanks :) consider starring this repo. hahaha jk.
