### ISSUE TITLE
An abnormality in the state value of the aircraft

### ISSUE THREAD

**Issue by piggymide** [sryu1/jsbgym#11]
First of all, I would like to thank you for the great work.

I modified some of the example code you presented and turned it around as follows, and a problem occurred in the process.

```
import jsbgym
import gymnasium as gym

env = gym.make("F16-HeadingControlTask-Shaping.STANDARD-NoFG-v0", render_mode="graph")
env.reset()
env.render()
done = False

while not done:
    action = np.array([1, 0, 0])
    observation, reward, terminated, truncated, info = env.step(action)
    print(observation)
```

When the simulation was performed using the F16 model and the action was arbitrarily entered [1, 0, 0] which is 1 for aileron_cmd, 0 for elevator_cmd and 0 for rudder_cmd, and when I checked the output value of the state, only the right side of the aileron have deflection and the left side of the aileron remains zero.

In addition to the F16 aircraft, this problem also occurs on F15 and B747. Only the c172 aircraft has an acceptable value. 
Do you happen to know why?

**Comment by piggymide** [comment]
In addition, if you use the print command to check the observation variable, you can see that the values of left aileron and r.aileron are different. It wouldn't be a problem if it was simply diffrent value, but I think there is a something wrong that the displacement of left aileron is fixed at 0.0.

**Comment by sryu1** [comment]
Hi, Thanks for pointing this out to me. Since this is derived from Gor-Ren's gym-jsbsim, I didn't really look deeply into that. I'll look into it in the future and see if I can fix it. It might take a week or two, or I might do it later this year (November/December) since I'm a little busy nowadays. Hope you understand :). 

Suggestion for your code since done does not change, you have to change it to terminated:

```py
import jsbgym
import gymnasium as gym

env = gym.make("F16-HeadingControlTask-Shaping.STANDARD-NoFG-v0", render_mode="graph")
env.reset()
env.render()
terminated = False

while not terminated:
    action = np.array([1, 0, 0])
    observation, reward, terminated, truncated, info = env.step(action)
    print(observation)
```

**Comment by sryu1** [comment]
In this commit, https://github.com/sryu1/jsbgym/commit/5c9753ce5300fa03e6e201075e8c1196473e77cd I have removed the surface position observations along with other irrelavent ones. I've tested if the values work and found that it's just the values that don't work. In the simulation, the manual inputs for actions work.
