### ISSUE TITLE
Multiplayer Flight Gear

### ISSUE THREAD

**Issue by ghost** [sryu1/jsbgym#3]
I want to open multiple instances on flight gear. For example run code in two windows on flight gear to fly two planes on same machine. when I run your file first time , the flight gear window opens and plane start flying. when I run the file again the new window of flight gear opens and plane is on ground not flying. Then I change the port number in your visualiser.py file it did not work because it work only on 5550 if you change the port then plane is grounded not fly. PLEASE HELP ME IN THIS CASE
Thanks alot 
<img width="1121" alt="Screenshot 2023-03-01 023615" src="https://user-images.githubusercontent.com/126635802/222030723-02f46e87-12c7-4e90-88bd-0081d6cc6abf.png">

THIS IS YOUR CODE IN visualiser.py
<img width="856" alt="Screenshot 2023-03-01 023355" src="https://user-images.githubusercontent.com/126635802/222030840-e688811e-264b-41c0-9567-8f612bea7cff.png">

**Comment by sryu1** [comment]
Hi, can you tell me how exactly you opened two instances?

**Comment by sryu1** [comment]
@Pgmr112233

**Comment by sryu1** [comment]
Closing issue as there is no response.
